apiVersion: v1
kind: Pod
metadata: 
  name: pod-nginx
  namespace: nscreation
  labels:
    namespace: test
spec: 
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP



apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: nscreation
spec: 
  selector:
    namespace: test
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
