apiVersion: v1
kind: Pod
metadata: 
  name: podnginx
  namespace: nscreation
  labels:
    myspace: test
spec: 
  containers:
  - name: nginxpod
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP



apiVersion: v1
kind: Service
metadata:
  name: servicenginx
  namespace: nscreation
spec: 
  selector:
    myspace: test
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
